In [18]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Flatten,Dropout,Activation
from keras.optimizers import SGD

import numpy as np
#生成1000行、20列的(0,1)之间随机值,相当于1000个样本，每个样本在输入端有20个样本特征
x_train=np.random.random((1000,20))
#生产10x1维矩阵，在[0,10)取值，1000个样本对应1000个标签
y_tmp=np.random.randint(10,size=(1000,1))
#y_tmp=np.random.randint(10,size=(10,1))
#print(y_tmp)
# [[2]
#  [0]
#  [4]
#  [3]
#  [4]
#  [1]
#  [0]
#  [0]
#  [8]
#  [4]]

#将10个数字one-hot编码(10个类别)，每行对应上述中一个数字
y_train=keras.utils.to_categorical(y_tmp,num_classes=10)
# print(y_train) 
# [[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
#  [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
#  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
#  [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
#  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
#  [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
#  [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
#  [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
#  [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
#  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]




In [19]:
x_test=np.random.random((100,20))
y_test=keras.utils.to_categorical(np.random.randint(10,size=(100,1)),num_classes=10)

In [22]:
'''
构建网络模型
'''
model=Sequential()
#第一层为包含64个隐藏神经元的全连接层，输入数据尺寸为20
model.add(Dense(64,activation='relu',input_dim=20))
model.add(Dropout(0.1))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(10,activation='softmax'))

#损失函数
sgd=SGD(lr=0.01,decay=1e-6,momentum=0.9,nesterov=True)
model.compile(loss='categorical_crossentropy',
             optimizer=sgd,
             metrics=['accuracy'])
model.fit(x_train,y_train,epochs=20,batch_size=128)
score=model.evaluate(x_test,y_test,batch_size=128)
print('Test loss: ',score[0])
print('Test accuracy: ',score[1])


Epoch 1/20
1000/1000 [==============================] - 0s 380us/step - loss: 2.3322 - acc: 0.0950
Epoch 2/20
1000/1000 [==============================] - 0s 25us/step - loss: 2.3200 - acc: 0.1070
Epoch 3/20
1000/1000 [==============================] - 0s 26us/step - loss: 2.3062 - acc: 0.1150
Epoch 4/20
1000/1000 [==============================] - 0s 26us/step - loss: 2.2984 - acc: 0.1180
Epoch 5/20
1000/1000 [==============================] - 0s 27us/step - loss: 2.3059 - acc: 0.1120
Epoch 6/20
1000/1000 [==============================] - 0s 26us/step - loss: 2.3045 - acc: 0.1120
Epoch 7/20
1000/1000 [==============================] - 0s 28us/step - loss: 2.3001 - acc: 0.1170
Epoch 8/20
1000/1000 [==============================] - 0s 27us/step - loss: 2.2996 - acc: 0.1270
Epoch 9/20
1000/1000 [==============================] - 0s 26us/step - loss: 2.2961 - acc: 0.1160
Epoch 10/20
1000/1000 [==============================] - 0s 27us/step - loss: 2.2964 - acc: 0.1130
Epoch 11/20
1000/1